name: Create Release

on:
  schedule:
    - cron: 0 12 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Creating Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_TAG  }}
          release_name: ${{ env.RELEASE_TAG }}
          body_path: .github/release.md
          draft: false
          prerelease: false
          
